language: python
python:
  - "3.8"

# Command to install dependencies
install:
  - pip3 install -r requirements.txt

# Runs before merging
script:
  - python3 -m unittest tests/heart_test.py
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip

# Run when is merged with master
deploy:
  - provider: s3
    access_key_id: $AccessKeyId
    secret_access_key: $AccessKeySecret
    local_dir: dpl_cd_upload
    skip_cleanup: true
    bucket: heartdiseasepredictor
    region: us-east-1
  - provider: codedeploy
    access_key_id: $AccessKeyId
    secret_access_key: $AccessKeySecret
    bucket: heartdiseasepredictor
    key: latest.zip
    bundle_type: zip
    application: heartdiseasepredictor
    deployment_group: travisheartdiseasegroup
    region: us-east-1