version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/predictor
    runas: ubuntu
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300